### ISSUE TITLE
Tracking issue for release 0.1.0

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/gateway-api-inference-extension#73]
```[tasklist]
### Must Haves
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/256
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/263
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/162
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/202
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/77
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/72
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/185
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/100
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/186
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/55
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/68
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/69
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/75
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/22
```

```[tasklist]
### Nice to haves
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/96
- [ ] https://github.com/kubernetes-sigs/llm-instance-gateway/issues/80
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/196
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/119
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/224
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/225
```

**Comment by ahg-g** [comment]
/close 

Released!
