### ISSUE TITLE
Add  hermetic tests on the routing algorithm

### ISSUE THREAD

**Issue by liu-cong** [kubernetes-sigs/gateway-api-inference-extension#80]
[Hermetic test](https://github.com/kubernetes-sigs/llm-instance-gateway/blob/main/pkg/ext-proc/test/hermetic_test.go) is a fast way to verify functionality e2e without requiring an integration test env. In addition to the basic test we have today, we should add the following:

Test framework improvements:
- [x] Run a fake k8s API server so we don't need to fake the reconcilers, done in https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/222

Test Cases
- [x] Happy path: Configure one InferencePool and InferenceModel, and verify request success
- [x] Test algorithm
  - [x] Verify min KV cache algo without LoRA - EPP should pick the pod with least kv-cache, refer to the [filter_test.go](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/pkg/ext-proc/scheduling/filter_test.go) for the conditions of the pod metrics.
  - [x] Verify LoRA affinity algo - EPP should pick the pod with LoRA already active.
  - [x]   Sheddable request succeeds when resource is available; and dropped when resource is constrained. 

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/153
```

**Comment by ahg-g** [comment]
Please take a look at integration test setup in jobset as an example: https://github.com/kubernetes-sigs/jobset/tree/main/test/integration/controller

**Comment by danehans** [comment]
I may not be able to add every requested test case but I can get this effort started.

/assign

**Comment by danehans** [comment]
@liu-cong thanks for the heads-up. @BenjaminBraunDev can you provide a status update when you have a moment? Do you have a local branch or WIP PR that can be referenced to see how we can divide and conquer this issue?

**Comment by danehans** [comment]
Unassigning myself why I work on the initial [e2e tests](https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/77).

**Comment by BenjaminBraunDev** [comment]
@danehans Yes, I'm currently working on specifically getting a k8s Client working with the tests for InferencePool and InferenceModel CRDs. Instead of using the StartExtProc() function in test utils, I'm moving a lot of the functionality from main.go into a new package "server" and calling it with specific vars in main.go as well as in the hermetic tests. This allows the test to pipe its own environment config into the functionality of main which more accurately reflects en e2e test, and from there the hermetic test creates a k8s client using the same environment.

But in short yes, I'm working on the hermetic tests at the moment, but no I don't have a PR yet.

**Comment by danehans** [comment]
> I'm moving a lot of the functionality from main.go into a new package "server" and calling it with specific vars in main.go as well as in the hermetic tests.

@BenjaminBraunDev note that https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/148 refactors main().

**Comment by ahg-g** [comment]
@BenjaminBraunDev how many of the tests listed are covered? can we close this?

**Comment by liu-cong** [comment]
> @BenjaminBraunDev how many of the tests listed are covered? can we close this?

I updated the list. Two major items left: test error cases, verify metrics. We covered the most important test cases, which is covering the different algorithm aspsects. I propose we repurpose this to "integrate test happy paths" and close it. 

I can open new issues for the remaining, so we can get more contributors to work on these.

Thoughts? @ahg-g @danehans

**Comment by ahg-g** [comment]
yeah, I think we should open separate issues for the specific tests we want to add.
